name: Amenenaia
on: workflow_dispatch

env:
   NAME: Will

jobs:
   say-hello:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - name: "Dis Bonjour"
           if: ${{ env.NAME != 'Will' }}
           run: echo "My name is $NAME !"
