name: Amensia
on: workflow_dispatch

env:
   NAME: Will

jobs:
   say-hello:
      runs-on: ubuntu-latest
      env:
         ENTREPRISE: Creek
      steps:
         - uses: actions/checkout@v2
         - name: Hi
           run: echo "My name is $NAME ! Je boss pour $ENTREPRISE"
           env:
               DAY: Sunday
          - name: "Sunday ?"
            run: echo "Today is $DAY"